AWSTemplateFormatVersion: 2010-09-09

Description:   CloudFormation Template for Roman Numerals Converter Application. This template creates Python Flask Web Application on Amazon Linux 2 (XXXXXXXXXXXXXXXXX) EC2 Instance with custom security group allowing http connections on port 80.
  Roman Numerals Converter Application is downloaded from Github repository, then installed on Flask.

Resources:
  ProjectInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c94855ba95c71c99
      InstanceType: t2.micro
      KeyName: ilkpair
      SecurityGroups: 
        - launch-wizard-3
      UserData:
         Fn::Base64:
          !Sub |
             #! /bin/bash -xe
            
              mkdir templates
              cd templates/
              wget https://raw.githubusercontent.com/albertsunn/aws-workshop/master/aws/projects/001-roman-numerals-converter/templates/index.html
              wget https://raw.githubusercontent.com/albertsunn/aws-workshop/master/aws/projects/001-roman-numerals-converter/templates/result.html
              cd ..
              wget https://raw.githubusercontent.com/albertsunn/aws-workshop/master/aws/projects/001-roman-numerals-converter/app.py
              sudo yum update -y
              sudo yum install python3 -y
              sudo pip3 install flask
              sudo python3 app.py
            
      Tags:
        - Key: Name
          Value: projectApache